### ISSUE TITLE
Failing CI tests

### ISSUE THREAD

**Issue by donpui** [LeastAuthority/wormhole-william#103]
Some tests time to time failed to run in CI. 
Case one can be replicated locally by repeatedly running specific test: _TestWormholeFileTransportSendMidStreamCancel_

**Case 1**
https://github.com/LeastAuthority/wormhole-william/actions/runs/3883138904/jobs/6624372648#step:6:88

```
=== RUN   TestWormholeFileTransportSendMidStreamCancel/With_TCP_relay_server
Downloading... via TCP relay tcp://0.0.0.0:49233
panic: write tcp 127.0.0.1:49232->127.0.0.1:49234: use of closed network connection

goroutine 404 [running]:
github.com/psanford/wormhole-william/rendezvous/rendezvousservertest.(*TestServer).withWelcome.func1.1({0x1341700, 0xc0000add40})
	/Users/runner/work/wormhole-william/wormhole-william/rendezvous/rendezvousservertest/rendezvousservertest.go:300 +0x10e
github.com/psanford/wormhole-william/rendezvous/rendezvousservertest.(*TestServer).withWelcome.func1.5()
	/Users/runner/work/wormhole-william/wormhole-william/rendezvous/rendezvousservertest/rendezvousservertest.go:540 +0x6c
created by github.com/psanford/wormhole-william/rendezvous/rendezvousservertest.(*TestServer).withWelcome.func1
	/Users/runner/work/wormhole-william/wormhole-william/rendezvous/rendezvousservertest/rendezvousservertest.go:532 +0x1bf1
FAIL	github.com/psanford/wormhole-william/wormhole	5.457s
FAIL
Error: Process completed with exit code 1.
```

**Case 2**
https://github.com/LeastAuthority/wormhole-william/actions/runs/3872001816/jobs/6600342446

```
=== RUN   TestVerifierAbort
panic: websocket: close sent

goroutine 84 [running]:
github.com/psanford/wormhole-william/rendezvous/rendezvousservertest.(*TestServer).withWelcome.func1.1(0x8333720, 0x8c93[40](https://github.com/LeastAuthority/wormhole-william/actions/runs/3872001816/jobs/6600342446#step:8:41)0)
	/home/runner/work/wormhole-william/wormhole-william/rendezvous/rendezvousservertest/rendezvousservertest.go:261 +0xe8
github.com/psanford/wormhole-william/rendezvous/rendezvousservertest.(*TestServer).withWelcome.func1.5(0x8f82540, 0x8eee030)
	/home/runner/work/wormhole-william/wormhole-william/rendezvous/rendezvousservertest/rendezvousservertest.go:499 +0x3b
created by github.com/psanford/wormhole-william/rendezvous/rendezvousservertest.(*TestServer).withWelcome.func1
	/home/runner/work/wormhole-william/wormhole-william/rendezvous/rendezvousservertest/rendezvousservertest.go:492 +0x1084
FAIL	github.com/psanford/wormhole-william/wormhole	0.091s
FAIL
```

**Comment by donpui** [comment]
https://github.com/gorilla#gorilla-toolkit is being archived. Rendezvousservertest use it. Probably we should refactor this and this might help solve connectivity issue.
cc @vu3rdd

**Comment by meejah** [comment]
Since we might soon replace Go entirely, I'm not sure this is a good thing to do in the immediate term.

**Comment by donpui** [comment]
As we have not yet replace Go and it is used in Winden and Destiny, small changes and fixes should be ok.

**Comment by meejah** [comment]
So it's "archived", but if there are no problems, what's the issue? Why do work we don't need to do on a thing that's likely to go away anyway..?

**Comment by donpui** [comment]
> So it's "archived", but if there are no problems, what's the issue? Why do work we don't need to do on a thing that's likely to go away anyway..?

What is archived?

**Comment by meejah** [comment]
You said "gorilla toolkit is being archived". That's not material if there aren't any issues..?

**Comment by donpui** [comment]
> You said "gorilla toolkit is being archived". That's not material if there aren't any issues..?

Yes, gorilla toolkit archived. Issues we have with websocket closure in CI on rendezvous server mock, which the only one use it.

**Comment by donpui** [comment]
> So is "archived" relevant or not then? I don't see how it's relevant.

I am not sure what you try to prove here. 
There are issues with websocket connectivity in CI, there is an recent fact about "archived" websocket library, which used only in test server mockup and is not used in the rest of go code. There is PR: https://github.com/LeastAuthority/wormhole-william/pull/105 which address this issue. 

Sharing information, that one of our dependency is being archived and not maintained anymore, I think is also important.

**Comment by meejah** [comment]
I'm not trying to "prove" anything, just don't want to waste unnecessary time refactoring tests. If there are reasons beyond "it's archived", fine, but your initial comment sounded like that was the reason to spend time removing a library.
